# Generated by Django 5.0.6 on 2024-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_country_user_phone_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/avatar/user_avatar_default.jpg",
                null=True,
                upload_to="users/avatar/",
                verbose_name="аватар",
            ),
        ),
    ]
