# Generated by Django 5.0.6 on 2024-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="mail_periodicity",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                default="Раз в день",
                verbose_name="Периодичность",
            ),
        ),
    ]
