# Generated by Django 5.0.6 on 2024-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newsletter",
            "0002_alter_mail_options_rename_surname_client_patronymic_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mail",
            options={
                "permissions": [
                    ("set_deactivate", "Can deactivate mail"),
                    ("view_all_mail", "Can view all mail"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="logattempt",
            name="attempt_status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Безуспешно", "Безуспешно")],
                max_length=50,
                verbose_name="Cтатус попытки",
            ),
        ),
    ]
