# Generated by Django 5.0.6 on 2024-06-01 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_mail_options_alter_logattempt_attempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="mail_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="mail_datetime_last",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Следующая отправка",
            ),
        ),
    ]
